###删除项目经理  BY ID删除
POST http://localhost:8080/api/admin/deleteManager
Content-Type: application/json
Authorization: {{token}}

{
  "id": 5,
  "user": {
    "id": 5
  }
}

###查找所有项目经理
GET http://localhost:8080/api/admin/getManagers
Authorization: {{token}}
Accept: application/json

###添加项目经理
POST http://localhost:8080/api/admin/addManager
Content-Type: application/json
Authorization: {{token}}

{
  "user": {
    "name": "SUu34",
    "number": 2017034
  }
}

### 全局变量，如果http测试文件被改动，可能失效。须重修登录
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "number" : "1001",
  "password": "1001"
}

> {% client.global.set("token", response.headers.valueOf("Authorization")); %}

###